# Generated by Django 4.2 on 2024-03-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learntenses', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(choices=[('PS', 'Present Simple'), ('PC', 'Present Continuous'), ('PP', 'Present Perfect'), ('PaS', 'Past Simple'), ('PaC', 'Past Continuous'), ('PaP', 'Past Perfect'), ('FS', 'Future Simple'), ('FC', 'Future Continuous'), ('FP', 'Future Perfect')], max_length=3)),
                ('sentence', models.CharField(max_length=500)),
                ('words', models.CharField(max_length=500)),
                ('correct_words', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learntenses.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learntenses.userprofile')),
            ],
        ),
    ]
