# Generated by Django 4.2 on 2024-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntenses', '0003_task_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('1', 'Task 1'), ('2', 'Task 2'), ('3', 'Task 3'), ('4', 'Task 4'), ('5', 'Task 5'), ('6', 'Task 6')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
