# Generated by Django 4.2 on 2024-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntenses', '0004_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
