# Generated by Django 4.2 on 2024-03-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntenses', '0005_task_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
    ]
