# Generated by Django 4.2 on 2024-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntenses', '0006_remove_task_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
